modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/Command17/Magnetizing/issues"
license = "MIT"

[[mods]]
modId = "magnetizing"
version = "${version}"
displayName = "Magnetizing"
authors = "Command17"
description = '''
Adds items and blocks based around magnets
'''

logoFile = "assets/magnetizing/icon.png"

[[dependencies.magnetizing]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.magnetizing]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.magnetizing]]
modId = "architectury"
type = "required"
versionRange = "[19.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "magnetizing.mixins.json"
